#ifndef ZIPLODE_ACTIONIDS_H
#define ZIPLODE_ACTIONIDS_H

enum ZL_MENU_ACTION
{
    ZL_ACTION_OPEN = 1001,
    ZL_ACTION_ARCHIVE = 1002,
    ZL_ACTION_HOME = 1003,
    ZL_ACTION_BACK = 1004,
    ZL_ACTION_UP = 1005,
};

#endif //ZIPLODE_ACTIONIDS_H
