#ifndef ZIPLODE_ACTIONIDS_H
#define ZIPLODE_ACTIONIDS_H

enum ZL_MENU_ACTION
{
    ZL_ACTION_OPEN = 1001,
    ZL_ACTION_ARCHIVE = 1002,
    ZL_ACTION_HOME = 1003,
    ZL_ACTION_BACK = 1004,
    ZL_ACTION_UP = 1005,
    ZL_ACTION_FORWARD = 1006,
};

enum ZL_EVENT_TYPE
{
    ZL_EVENT_PATH_CHANGED = 0,
    ZL_EVENT_CONTENT_LOADED = 1,
};

#endif //ZIPLODE_ACTIONIDS_H
